export const SERACH_TITLE = 'SEARCH_TITLE'
export const SERACH_DATA_LOADING = 'SEARCH_DATA_LOADING'
export const SERACH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS'
export const SERACH_DATA_ERROR = 'SEARCH_DATA_ERROR'